spring:
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  prometheus:
    metrics:
      export:
        enabled: true